-- MySQL Script generated by MySQL Workbench
-- qua 28 jun 2017 19:08:13 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_professor` (
  `id_professor` INT NOT NULL,
  `email` VARCHAR(150) NULL,
  `nome` VARCHAR(150) NULL,
  `login` VARCHAR(255) NULL,
  `senha` VARCHAR(255) NULL,
  PRIMARY KEY (`id_professor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_turma` (
  `id_turma` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `semestre` VARCHAR(45) NULL,
  `ano` INT(4) NULL,
  `tb_professor_id_professor` INT NOT NULL,
  PRIMARY KEY (`id_turma`, `tb_professor_id_professor`),
  INDEX `fk_tb_turma_tb_professor1_idx` (`tb_professor_id_professor` ASC),
  CONSTRAINT `fk_tb_turma_tb_professor1`
    FOREIGN KEY (`tb_professor_id_professor`)
    REFERENCES `mydb`.`tb_professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_aluno` (
  `id_aluno` INT NOT NULL,
  `nome` VARCHAR(150) NULL,
  `matricula` VARCHAR(150) NULL,
  `foto` VARCHAR(1000) NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_curso` (
  `id_curso` INT NOT NULL,
  `nome` VARCHAR(150) NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_disciplina` (
  `id_disciplina` INT NOT NULL,
  `nome` VARCHAR(150) NULL,
  `descricao` VARCHAR(150) NULL,
  `tb_curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_disciplina`, `tb_curso_id_curso`),
  INDEX `fk_tb_disciplina_tb_curso1_idx` (`tb_curso_id_curso` ASC),
  CONSTRAINT `fk_tb_disciplina_tb_curso1`
    FOREIGN KEY (`tb_curso_id_curso`)
    REFERENCES `mydb`.`tb_curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_chamada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_chamada` (
  `id_chamada` INT NOT NULL,
  `data` VARCHAR(45) NULL,
  `presenca` CHAR(1) NULL,
  `tb_professor_id_professor` INT NOT NULL,
  `tb_aluno_id_aluno` INT NOT NULL,
  `tb_disciplina_id_disciplina` INT NOT NULL,
  `tb_disciplina_tb_curso_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_chamada`, `tb_professor_id_professor`, `tb_aluno_id_aluno`, `tb_disciplina_id_disciplina`, `tb_disciplina_tb_curso_id_curso`),
  INDEX `fk_tb_chamada_tb_professor1_idx` (`tb_professor_id_professor` ASC),
  INDEX `fk_tb_chamada_tb_aluno1_idx` (`tb_aluno_id_aluno` ASC),
  INDEX `fk_tb_chamada_tb_disciplina1_idx` (`tb_disciplina_id_disciplina` ASC, `tb_disciplina_tb_curso_id_curso` ASC),
  CONSTRAINT `fk_tb_chamada_tb_professor1`
    FOREIGN KEY (`tb_professor_id_professor`)
    REFERENCES `mydb`.`tb_professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_chamada_tb_aluno1`
    FOREIGN KEY (`tb_aluno_id_aluno`)
    REFERENCES `mydb`.`tb_aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_chamada_tb_disciplina1`
    FOREIGN KEY (`tb_disciplina_id_disciplina` , `tb_disciplina_tb_curso_id_curso`)
    REFERENCES `mydb`.`tb_disciplina` (`id_disciplina` , `tb_curso_id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_turma_tem_tb_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_turma_tem_tb_aluno` (
  `tb_turma_id_turma` INT NOT NULL,
  `tb_aluno_id_aluno` INT NOT NULL,
  PRIMARY KEY (`tb_turma_id_turma`, `tb_aluno_id_aluno`),
  INDEX `fk_tb_turma_has_tb_aluno_tb_aluno1_idx` (`tb_aluno_id_aluno` ASC),
  INDEX `fk_tb_turma_has_tb_aluno_tb_turma1_idx` (`tb_turma_id_turma` ASC),
  CONSTRAINT `fk_tb_turma_has_tb_aluno_tb_turma1`
    FOREIGN KEY (`tb_turma_id_turma`)
    REFERENCES `mydb`.`tb_turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_turma_has_tb_aluno_tb_aluno1`
    FOREIGN KEY (`tb_aluno_id_aluno`)
    REFERENCES `mydb`.`tb_aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_turma_has_tb_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_turma_has_tb_disciplina` (
  `tb_turma_id_turma` INT NOT NULL,
  `tb_disciplina_id_disciplina` INT NOT NULL,
  PRIMARY KEY (`tb_turma_id_turma`, `tb_disciplina_id_disciplina`),
  INDEX `fk_tb_turma_has_tb_disciplina_tb_disciplina1_idx` (`tb_disciplina_id_disciplina` ASC),
  INDEX `fk_tb_turma_has_tb_disciplina_tb_turma1_idx` (`tb_turma_id_turma` ASC),
  CONSTRAINT `fk_tb_turma_has_tb_disciplina_tb_turma1`
    FOREIGN KEY (`tb_turma_id_turma`)
    REFERENCES `mydb`.`tb_turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_turma_has_tb_disciplina_tb_disciplina1`
    FOREIGN KEY (`tb_disciplina_id_disciplina`)
    REFERENCES `mydb`.`tb_disciplina` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
